
name: Create release

on:
  release:
    types:
      - created

env:
  PLUGIN_NAME: social.bsky.pds

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Zip Folder
        run: zip -j ${{ env.PLUGIN_NAME }}.tapestry ${{ env.PLUGIN_NAME }}/*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.PLUGIN_NAME }}.tapestry
        env:
          GITHUB_TOKEN: ${{ secrets.social.bsky.pds.tapestry }}